-- Bhanumati-Caousik coupons are not live yet. Run this when client codes are ready:
--
-- INSERT OR REPLACE INTO coupons (code, discount_type, value, min_amount, max_discount, active, expires_at, project_id, id, discount_value)
-- VALUES
--   ('BHANU10', 'percentage', 10, 0, NULL, 1, NULL, 'bhanumati-caousik', 'bhanumati-caousik-bhanu10', 10),
--   ('BHANU500', 'fixed', 500, 0, NULL, 1, NULL, 'bhanumati-caousik', 'bhanumati-caousik-bhanu500', 500);
